-- =====================================================================
-- 02_tables.sql  -  tables, constraints, indexes
-- Timestamps are WITHOUT TIME ZONE (the old backend used naive datetimes).
-- =====================================================================

-- ---------------------------------------------------------------------
-- Accounts (private: never exposed directly, password hashes live here)
-- ---------------------------------------------------------------------
CREATE TABLE private.users (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(50)  NOT NULL UNIQUE CHECK (char_length(username) >= 3),
    email          VARCHAR(255) NOT NULL,
    password_hash  TEXT         NOT NULL,                       -- bcrypt via pgcrypto crypt()
    role           VARCHAR(20)  NOT NULL DEFAULT 'User' CHECK (role IN ('User', 'Admin')),
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE
);
CREATE UNIQUE INDEX uq_users_email ON private.users (lower(email));

-- ---------------------------------------------------------------------
-- Reference data
-- ---------------------------------------------------------------------
CREATE TABLE api.countries (
    code                     VARCHAR(2)   PRIMARY KEY CHECK (code ~ '^[A-Z]{2}$'),
    name                     VARCHAR(100) NOT NULL,
    continent                VARCHAR(50),
    official_language        VARCHAR(100),
    is_schengen_zone_member  BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE api.airports (
    code                 VARCHAR(3)   PRIMARY KEY CHECK (code ~ '^[A-Z]{3}$'),
    name                 VARCHAR(200) NOT NULL,
    location             VARCHAR(200),
    country_code         VARCHAR(2)   REFERENCES api.countries (code),
    number_of_terminals  INTEGER      CHECK (number_of_terminals IS NULL OR number_of_terminals >= 1)
);
CREATE INDEX idx_airports_country ON api.airports (country_code);

CREATE TABLE api.airlines (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(200) NOT NULL,
    iata_code          VARCHAR(2)   UNIQUE,
    icao_code          VARCHAR(3)   UNIQUE,
    headquarters       VARCHAR(200),
    year_founded       INTEGER,
    base_airport_code  VARCHAR(3)   REFERENCES api.airports (code)
);
CREATE INDEX idx_airlines_base_airport ON api.airlines (base_airport_code);

CREATE TABLE api.currencies (
    currency_code  VARCHAR(3)       PRIMARY KEY,
    symbol         VARCHAR(10),
    exchange_rate  DOUBLE PRECISION CHECK (exchange_rate IS NULL OR exchange_rate > 0),
    country_name   VARCHAR(100),
    last_updated   TIMESTAMP
);

-- ---------------------------------------------------------------------
-- People
-- ---------------------------------------------------------------------
CREATE TABLE api.passengers (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   VARCHAR(100),
    national_id            VARCHAR(20)  UNIQUE,
    email                  VARCHAR(255),
    phone_number           VARCHAR(30),
    nationality            VARCHAR(50),
    is_vip                 BOOLEAN      NOT NULL DEFAULT FALSE,
    address                VARCHAR(255),
    date_of_birth          DATE,
    passport_number        VARCHAR(20),
    gender                 VARCHAR(20),
    frequent_flyer_number  VARCHAR(30)  UNIQUE,
    -- Who created this passenger; drives row-level security (see 04_security.sql)
    created_by             INTEGER      DEFAULT private.current_user_id()
                                        REFERENCES private.users (id) ON DELETE SET NULL
);
CREATE INDEX idx_passengers_email      ON api.passengers (lower(email));
CREATE INDEX idx_passengers_created_by ON api.passengers (created_by);

CREATE TABLE api.loyalty_programs (
    id                             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_name                   VARCHAR(100),
    passenger_id                   INTEGER UNIQUE REFERENCES api.passengers (id) ON DELETE CASCADE,
    points                         INTEGER NOT NULL DEFAULT 0 CHECK (points >= 0),
    tier_level                     VARCHAR(30),
    required_points_for_next_tier  INTEGER,
    membership_start_date          TIMESTAMP,
    available_rewards              JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE TABLE api.booking_agents (
    agent_id               VARCHAR(50)  PRIMARY KEY,
    name                   VARCHAR(100),
    agency                 VARCHAR(100),
    contact_number         VARCHAR(30),
    email                  VARCHAR(255),
    agency_license_number  VARCHAR(50),
    is_certified           BOOLEAN NOT NULL DEFAULT FALSE
);

-- ---------------------------------------------------------------------
-- Flights and seats
-- ---------------------------------------------------------------------
CREATE TABLE api.flights (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number      VARCHAR(10) NOT NULL UNIQUE CHECK (flight_number ~ '^[A-Za-z0-9]{2,10}$'),
    departure_code     VARCHAR(3)  NOT NULL REFERENCES api.airports (code),
    destination_code   VARCHAR(3)  NOT NULL REFERENCES api.airports (code),
    departure_time     TIMESTAMP,
    arrival_time       TIMESTAMP,
    total_seats        INTEGER     CHECK (total_seats IS NULL OR total_seats > 0),
    gate               VARCHAR(10),
    terminal           VARCHAR(10),
    airline_id         INTEGER     REFERENCES api.airlines (id),
    days_of_operation  INTEGER     CHECK (days_of_operation IS NULL OR days_of_operation BETWEEN 0 AND 127),  -- weekday bitmask
    user_id            INTEGER     REFERENCES private.users (id) ON DELETE SET NULL,
    CONSTRAINT flights_route_differs CHECK (departure_code <> destination_code),
    CONSTRAINT flights_arrival_after CHECK (arrival_time IS NULL OR departure_time IS NULL OR arrival_time > departure_time)
);
CREATE INDEX idx_flights_route_date ON api.flights (departure_code, destination_code, (departure_time::date));
CREATE INDEX idx_flights_departure  ON api.flights (departure_time);
CREATE INDEX idx_flights_airline    ON api.flights (airline_id);

CREATE TABLE api.seats (
    seat_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seat_number          VARCHAR(10) NOT NULL,
    class_type           VARCHAR(20) NOT NULL CHECK (class_type IN ('economy', 'premium economy', 'business', 'first')),
    is_available         BOOLEAN     NOT NULL DEFAULT TRUE,
    seat_type            VARCHAR(20) NOT NULL,
    additional_features  JSONB       NOT NULL DEFAULT '[]'::jsonb,
    reservation_time     TIMESTAMP,
    flight_id            INTEGER     NOT NULL REFERENCES api.flights (id) ON DELETE CASCADE,
    CONSTRAINT seats_unique_per_flight UNIQUE (flight_id, seat_number)
);
CREATE INDEX idx_seats_available ON api.seats (flight_id) WHERE is_available;

-- ---------------------------------------------------------------------
-- Reservations, tickets, payments, luggage
-- ---------------------------------------------------------------------
CREATE TABLE api.reservations (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passenger_id         INTEGER     REFERENCES api.passengers (id) ON DELETE CASCADE,
    flight_id            INTEGER     REFERENCES api.flights (id)    ON DELETE CASCADE,
    seat_number          VARCHAR(10) NOT NULL,
    status               VARCHAR(20) NOT NULL DEFAULT 'Pending'
                                     CHECK (status IN ('Pending', 'Confirmed', 'Canceled')),
    final_price          NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (final_price >= 0),
    created_at           TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    departure_country    VARCHAR(10) NOT NULL,
    destination_country  VARCHAR(10) NOT NULL
);
CREATE INDEX idx_reservations_passenger ON api.reservations (passenger_id);
CREATE INDEX idx_reservations_flight    ON api.reservations (flight_id);
-- A seat can only be held by one non-canceled reservation per flight.
CREATE UNIQUE INDEX uq_reservations_active_seat
    ON api.reservations (flight_id, seat_number) WHERE status <> 'Canceled';

CREATE TABLE api.tickets (
    ticket_number    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passenger_id     INTEGER REFERENCES api.passengers (id)   ON DELETE CASCADE,
    flight_id        INTEGER REFERENCES api.flights (id)      ON DELETE CASCADE,
    reservation_id   INTEGER REFERENCES api.reservations (id) ON DELETE CASCADE,
    seat_number      VARCHAR(10),
    ticket_class     VARCHAR(20) CHECK (ticket_class IN ('economy', 'premium economy', 'business', 'first')),
    status           VARCHAR(20) DEFAULT 'active',
    issue_date       TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    expiration_date  TIMESTAMP   DEFAULT (CURRENT_TIMESTAMP + INTERVAL '1 year'),
    base_price       NUMERIC(12,2) CHECK (base_price  IS NULL OR base_price  >= 0),
    final_price      NUMERIC(12,2) CHECK (final_price IS NULL OR final_price >= 0)
);
CREATE INDEX idx_tickets_reservation ON api.tickets (reservation_id);
CREATE INDEX idx_tickets_flight      ON api.tickets (flight_id);
CREATE INDEX idx_tickets_passenger   ON api.tickets (passenger_id);

CREATE TABLE api.payments (
    payment_id      VARCHAR(64) PRIMARY KEY DEFAULT gen_random_uuid()::text,
    reservation_id  INTEGER     REFERENCES api.reservations (id) ON DELETE CASCADE,
    amount          NUMERIC(12,2) CHECK (amount IS NULL OR amount > 0),
    method          VARCHAR(30) CHECK (method IN ('credit card', 'debit card', 'bank transfer', 'cash')),
    status          VARCHAR(20) DEFAULT 'pending',
    payment_date    TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    transaction_id  VARCHAR(100),
    currency        VARCHAR(3)  REFERENCES api.currencies (currency_code),
    is_refundable   BOOLEAN     NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_payments_reservation ON api.payments (reservation_id);

CREATE TABLE api.luggage (
    luggage_id     VARCHAR(50) PRIMARY KEY,
    passenger_id   INTEGER     REFERENCES api.passengers (id) ON DELETE CASCADE,
    ticket_id      INTEGER     REFERENCES api.tickets (ticket_number) ON DELETE CASCADE,
    weight         DOUBLE PRECISION CHECK (weight IS NULL OR weight >= 0),
    dimensions     VARCHAR(50),
    luggage_fee    NUMERIC(12,2) DEFAULT 0,
    status         VARCHAR(100),
    is_checked_in  BOOLEAN NOT NULL DEFAULT FALSE,
    is_fragile     BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_luggage_passenger ON api.luggage (passenger_id);
CREATE INDEX idx_luggage_ticket    ON api.luggage (ticket_id);

-- ---------------------------------------------------------------------
-- Promotions (special_promotions extends promotions)
-- ---------------------------------------------------------------------
CREATE TABLE api.promotions (
    promo_id             VARCHAR(50) PRIMARY KEY,
    description          VARCHAR(255),
    discount_percentage  DOUBLE PRECISION CHECK (discount_percentage IS NULL OR discount_percentage BETWEEN 0 AND 100),
    start_date           TIMESTAMP,
    end_date             TIMESTAMP,
    promo_code           VARCHAR(50),
    min_purchase         NUMERIC(12,2),
    max_discount         NUMERIC(12,2),
    usage_limit          INTEGER,
    usage_count          INTEGER NOT NULL DEFAULT 0,
    type                 VARCHAR(50) NOT NULL DEFAULT 'promotion',
    CONSTRAINT promotions_dates CHECK (start_date IS NULL OR end_date IS NULL OR end_date >= start_date)
);
CREATE UNIQUE INDEX uq_promotions_code ON api.promotions (promo_code);

CREATE TABLE api.special_promotions (
    promo_id     VARCHAR(50) PRIMARY KEY REFERENCES api.promotions (promo_id) ON DELETE CASCADE,
    extra_bonus  DOUBLE PRECISION NOT NULL
);
